DROP TABLE IF EXISTS WS_PEDIDO;
DROP TABLE IF EXISTS WS_PEDIDO_ITEM;

CREATE TABLE WS_PEDIDO (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  DH_CRIACAO TIMESTAMP,
  RAZAO_SOCIAL VARCHAR(250),
  CNPJ VARCHAR(250),
  TELEFONE VARCHAR(250),
  EMAIL VARCHAR(250)
);


CREATE TABLE WS_PEDIDO_ITEM (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  PRODUTO VARCHAR(250),
  QUANTIDADE NUMBER,
  PRECO NUMBER,
  DH_CRIACAO TIMESTAMP,
  ID_PEDIDO NUMBER,
  ID_PRODUTO NUMBER
);